"use client";
import {useState,useEffect,useRef} from 'react';
type Content={texts:Record<string,string>;theme:Record<string,string>;heroImage?:string;logoImage?:string};
export default function Editor(){const[content,setContent]=useState<Content>({texts:{},theme:{}});const[revision,setRevision]=useState('0');const[loaded,setLoaded]=useState(false);const[dirty,setDirty]=useState(false);const[saving,setSaving]=useState(false);const[status,setStatus]=useState('Caricamento…');const[selected,setSelected]=useState('');const[mobile,setMobile]=useState(false);const[selectMode,setSelectMode]=useState(true);const[history,setHistory]=useState<Content[]>([]);const frame=useRef<HTMLIFrameElement>(null);const current=useRef(content);current.current=content;
function post(){frame.current?.contentWindow?.postMessage({type:'aaa-content',content:current.current},location.origin)}
useEffect(()=>{fetch('/api/content',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Caricamento non riuscito. Ricarica la pagina.');return r.json()}).then((d:any)=>{setContent(d.content);setRevision(d.revision);setLoaded(true);setStatus('Seleziona un testo nell’anteprima per modificarlo.');}).catch(e=>setStatus(e.message));const receive=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='aaa-selected')setSelected(e.data.key);if(e.data?.type==='aaa-ready')post()};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[]);
useEffect(()=>{if(loaded)post()},[content,loaded]);useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
function change(next:Content){setHistory(h=>[...h.slice(-29),content]);setContent(next);setDirty(true);setStatus('Anteprima aggiornata · modifiche non ancora salvate.')}function undo(){if(!history.length)return;setContent(history[history.length-1]);setHistory(history.slice(0,-1));setDirty(true)}
async function save(){setSaving(true);setStatus('Salvataggio…');try{const r=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,revision})});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Salvataggio non riuscito.');setRevision(d.revision);setDirty(false);setStatus('Salvato sul sito. Le pagine già aperte si aggiornano entro 15 secondi.')}catch(e){setStatus(e instanceof Error?e.message:'Errore di salvataggio.')}finally{setSaving(false)}}
async function upload(file:File|undefined,key:'heroImage'|'logoImage'){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>600000){setStatus('Usa PNG, JPEG o WebP fino a 600 KB.');return}const reader=new FileReader();reader.onload=()=>change({...content,[key]:String(reader.result)});reader.readAsDataURL(file)}
return <div className="studio"><div className="studiohead"><div><strong>AAA Partners</strong><span>Editor del sito</span></div><div><a href="/" target="_blank" rel="noreferrer">Apri sito ↗</a><button disabled={!history.length||saving} onClick={undo}>Annulla modifica</button><button className="save" disabled={!loaded||saving||!dirty} onClick={save}>{saving?'Salvataggio…':dirty?'Salva sul sito ●':'Tutto salvato ✓'}</button></div></div><div className="studiobody"><aside><div className="studiostatus" role="status">{status}</div><fieldset disabled={!loaded||saving}><h2>Modifica in tempo reale</h2><p>Clicca un testo nella pagina. Scrivi qui sotto e guarda subito il risultato.</p><label>Testo selezionato<textarea rows={7} disabled={!selected} value={selected?(content.texts[selected]??selected):''} placeholder="Seleziona un titolo, una descrizione o un pulsante…" onChange={e=>change({...content,texts:{...content.texts,[selected]:e.target.value}})}/></label>{selected&&<button onClick={()=>{const texts={...content.texts};delete texts[selected];change({...content,texts})}}>Ripristina questo testo</button>}<p className="editorhint">I testi identici si aggiornano insieme. I campi del modulo e le categorie dei contatti restano protetti.</p><h3>Colori del sito</h3>{Object.entries({navy:'Blu principale',gold:'Accenti',paper:'Sfondo',ink:'Testi'}).map(([k,label])=><label className="colorrow" key={k}>{label}<input type="color" value={content.theme[k]||({navy:'#071a2c',gold:'#c9af7c',paper:'#f7f7f2',ink:'#102a37'} as any)[k]} onChange={e=>change({...content,theme:{...content.theme,[k]:e.target.value}})}/></label>)}<h3>Immagini</h3><label>Foto di apertura<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0],'heroImage')}/></label><label>Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0],'logoImage')}/></label><p className="editorhint">PNG, JPEG o WebP · massimo 600 KB per immagine.</p><button onClick={()=>change({...content,heroImage:undefined,logoImage:undefined})}>Ripristina immagini originali</button></fieldset></aside><div className="previewarea"><div className="previewtools"><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Smartphone</button><label><input type="checkbox" checked={selectMode} onChange={e=>{setSelectMode(e.target.checked);frame.current?.contentWindow?.postMessage({type:'aaa-select-mode',enabled:e.target.checked},location.origin)}}/>Seleziona testi</label></div><iframe ref={frame} src="/?editor=1" title="Anteprima modificabile di AAA Partners" className={mobile?'phonepreview':''} onLoad={post}/></div></div></div>}
