import {getDb} from '../../../db';
import {siteContent} from '../../../db/schema';
import {eq} from 'drizzle-orm';
import {getChatGPTUser} from '../../chatgpt-auth';
export const dynamic='force-dynamic';
const owner='dott.pgcala@gmail.com';
const headers={'Cache-Control':'no-store'};
export async function GET(){try{const [row]=await getDb().select().from(siteContent).where(eq(siteContent.id,'main'));return Response.json({content:row?JSON.parse(row.json):{texts:{},theme:{}},revision:row?.revision||'0'},{headers})}catch{return Response.json({error:'Contenuti non disponibili.'},{status:503,headers})}}
export async function PUT(request:Request){const user=await getChatGPTUser();if(!user||user.email.toLowerCase()!==owner)return Response.json({error:'Accesso riservato al proprietario.'},{status:403,headers});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origine non valida.'},{status:403,headers});
let data:any;try{const raw=await request.text();if(raw.length>1900000)throw Error();data=JSON.parse(raw);const c=data.content;if(!c||typeof c.texts!=='object'||Array.isArray(c.texts)||!c.theme||typeof c.theme!=='object'||typeof data.revision!=='string')throw Error();if(Object.keys(c.texts).length>500)throw Error();for(const [k,v] of Object.entries(c.texts)){if(k.length>5000||typeof v!=='string'||v.length>5000)throw Error()}for(const [k,v] of Object.entries(c.theme)){if(!['navy','gold','paper','ink'].includes(k)||typeof v!=='string'||!/^#[0-9a-fA-F]{6}$/.test(v))throw Error()}for(const k of ['heroImage','logoImage'])if(c[k]&&!(typeof c[k]==='string'&&c[k].length<810000&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(c[k])))throw Error()}catch{return Response.json({error:'Contenuto non valido o immagine troppo grande.'},{status:400,headers})}
try{const db=getDb();const rev=crypto.randomUUID();const values={json:JSON.stringify(data.content),revision:rev,updatedAt:new Date().toISOString()};if(data.revision==='0'){const rows=await db.insert(siteContent).values({id:'main',...values}).onConflictDoNothing().returning();if(!rows.length)return Response.json({error:'Il sito è stato modificato altrove. Ricarica prima di salvare.'},{status:409,headers})}else{const {and}=await import('drizzle-orm');const rows=await db.update(siteContent).set(values).where(and(eq(siteContent.id,'main'),eq(siteContent.revision,data.revision))).returning();if(!rows.length)return Response.json({error:'Il sito è stato modificato altrove. Ricarica prima di salvare.'},{status:409,headers})}return Response.json({ok:true,revision:rev},{headers})}catch{return Response.json({error:'Salvataggio non riuscito. Le modifiche restano nell’anteprima.'},{status:503,headers})}}
